# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: generic
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - WARNINGS_OK=false
    - ROS_DISTRO=dashing
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=moveit_msgs.repos
  matrix:
    # - TEST=catkin_lint
    - ROS_DISTRO=dashing

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh
